### ISSUE TITLE
Error loading the gem on Rails 4

### ISSUE THREAD

**Issue by bluegod** [prawnpdf/prawn-table#40]
I'm not sure if I missed something here but I get the following error after adding the gem to my Gemfile:

    NoMethodError: undefined method `extensions' for Prawn::Document:Class
    /Users/my_user/.rvm/gems/ruby-2.1.2@cmi/gems/prawn-table-0.2.1/lib/prawn/table.rb:700:in `<top (required)>'
    /Users/my_user/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:85:in `require'
    /Users/my_user/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:85:in `rescue in block in require'
    /Users/my_user/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:68:in `block in require'
    /Users/my_user/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:61:in `each'
    /Users/my_user/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:61:in `require'
    /Users/my_user/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler.rb:132:in `require'
    /Users/my_user/Development/my_app/config/application.rb:8:in `<top (required)>'
    /Users/my_user/Development/my_app/Rakefile:4:in `require'
    /Users/my_user/Development/my_app/Rakefile:4:in `<top (required)>'
    /Users/my_user/.rvm/gems/ruby-2.1.2@cmi/bin/ruby_executable_hooks:15:in `eval'
    /Users/my_user/.rvm/gems/ruby-2.1.2@cmi/bin/ruby_executable_hooks:15:in `<main>'
    LoadError: cannot load such file -- prawn-table
    /Users/my_user/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:76:in `require'
    /Users/my_user/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
    /Users/my_user/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:72:in `each'
    /Users/my_user/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:72:in `block in require'
    /Users/my_user/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:61:in `each'
    /Users/my_user/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:61:in `require'
    /Users/my_user/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler.rb:132:in `require'
    /Users/my_user/Development/my_app/config/application.rb:8:in `<top (required)>'
    /Users/my_user/Development/my_app/Rakefile:4:in `require'
    /Users/my_user/Development/my_app/Rakefile:4:in `<top (required)>'
    /Users/my_user/.rvm/gems/ruby-2.1.2@cmi/bin/ruby_executable_hooks:15:in `eval'
    /Users/my_user/.rvm/gems/ruby-2.1.2@cmi/bin/ruby_executable_hooks:15:in `<main>'
    (See full trace by running task with --trace)

Gem versions:

prawn (1.3.0)
prawn-table (0.2.1)
prawnto_2 (0.2.6)

Ruby 2.1.2
Rails 4.1.1
OS: MAC OS 10.9.5

This is what it's around line 8 of application.rb:

    # Require the gems listed in Gemfile, including any gems
    # you've limited to :test, :development, or :production.
    Bundler.require(:default, Rails.env)

**Comment by bluegod** [comment]
Ok fixed:

I had to add prawn even though it was implicitly required by prawnto.

gem "prawnto_2", :require => "prawnto"
gem 'prawn-table'

changed to:

gem 'prawn'
gem "prawnto_2", :require => "prawnto"
gem 'prawn-table'
